### ISSUE TITLE
Performance issue using View.parse

### ISSUE THREAD

**Issue by fattenap** [IjzerenHein/autolayout.js#10]
I've created a grid layout that looks something like this

```
V:|-[child1,child2,child3]-[child4]-|
H:|-[child1,child4]-[child2]-[child3]-|
```
I use View.parse to get the constraints and apply it to my view (I'm using React). Whenever I add a child I re-parse the VFL. With each child the performance degrades. It becomes unusable at around 30 elements.

Am I doing something wrong? Can I parse part of the VFL to obtain the constraints that I need? Any other suggestions are more than welcome.

Thanks

**Comment by IjzerenHein** [comment]
Hi, I don't think the performance of the parsing is the bottleneck here. i did experiments and found that parsing is actually really fast. I'm guessing that creating the View from the constraints is actually the bottleneck. Could you do some tests and test the speed of VisualFormat.parse and new View() individually?

Also, there is an experimental kiwi-version of autolayout available. It's in the dist folder. It's way faster than the cassowary-js based version. You could try using that version.

**Comment by fattenap** [comment]
Hi, 
Sorry I've taken so long to assess this. 

I have run some tests and found that the bottleneck is addConstraints.

What I'm doing is, I have a grid and I parse the format (VFL), which returns constraints which I then add to the view. So the next time I add an element to the grid, I re-parse the format, which includes the previous format and add the resulting constraints. I repeat this process for every new element added. I've tried adding just the last set of constraints returned, which increases performance but is not formatted correctly. Below is some pseudo code to help explain what I'm doing

```javascript
function updateVisualFormat(layoutFormat){

  //layoutFormat has the entire VFL for the grid and any new elements
  var constraints = AutoLayout.VisualFormat.parse(layoutFormat, {extended: true});
  var metaInfo = AutoLayout.VisualFormat.parseMetaInfo ? AutoLayout.VisualFormat.parseMetaInfo(layoutFormat) : {};

  myView.addConstraints(constraints);
  ...
}
```

Is adding all the constraints every time OK, is there a way to determine which constraints to add?

**Comment by IjzerenHein** [comment]
Hey,

In this particular case you're probably just better of just creating a new view every time. There is currently no method to remove constraints, but first removing them and the re-adding them is probably just as fast as just creating a new view.

Alternatively, you could format the vfl in such a way so each rows has dedicated vfl for it. Here's an example of what I mean:

```javascript
var view = new AutoLayout.View();
var rowIdx = 0;
```

Initial row:

```vfl
H:|[row1]|
V:|[row1(20)]
```
```javascript
rowIdx++;
view.addConstraints(AutoLayout.parse(...));
```

Insert second row

```vfl
H:|[row2]|
V:[row1][row2(row1)]
```
```javascript
rowIdx++;
view.addConstraints(AutoLayout.parse(...));
```

and so on..

**Comment by fattenap** [comment]
Hi,

Thanks for you response. It has helped clarify how to structure my VFL. Just what I needed. Appreciate your help and great library.

Frank
