### ISSUE TITLE
Example for nested stack view

### ISSUE THREAD

**Issue by Rayraegah** [IjzerenHein/autolayout.js#15]
Hey Hein, 

Can you give an EVFL example for the Nested Stack View seen here?
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/LayoutUsingStackViews.html#//apple_ref/doc/uid/TP40010853-CH11-SW1

**Comment by IjzerenHein** [comment]
Of course, here are a few examples:

```vfl
V:|-10-[col:[flower(30)][image][edit(30)]]-10-|
H:|-20-[col]-20-|
```

And a more complex one:

```vfl
//-viewport max-width:500

// main viewstack
V:|-[col:[upper(100)]-[notes]-[buttons(40)]]-|
H:|-[col]-|

// upper area
H:[upper:-[image(image.height)]-[nameRows]-]
V:[nameRows:[firstName][middleName(firstName)][lastName(firstName)]]
H:[firstName:[firstNameLabel][firstNameValue(firstNameLabel*2)]]
H:[middleName:[middleNameLabel][middleNameValue(middleNameLabel*2)]]
H:[lastName:[lastNameLabel][lastNameValue(lastNameLabel*2)]]

// buttons
H:[buttons:~[save(25%)]-[cancel(save)]-[clear(save)]~]
```

![image](https://cloud.githubusercontent.com/assets/6184593/14597650/669dcbc2-054e-11e6-8041-487c547e3116.png)

**Comment by Rayraegah** [comment]
Thank you! I've got the hang out EVFL now.

**Comment by IjzerenHein** [comment]
Awesome, glad that helped :)
If you create any other interesting EVFL examples that would also be helpful to other developers, feel free to post them here in this thread 👍 
cheers
