### ISSUE TITLE
[Question] Method for nesting views into others

### ISSUE THREAD

**Issue by benb7760** [IjzerenHein/autolayout.js#19]
I'm trying to work out whether it is possible to add Views to SubViews in order to create a nested view structure, but I'm struggling to work out whether this is possible or if I would have to extend the library in some way to achieve this

I am looking to do this with code directly, not with VFL

**Comment by IjzerenHein** [comment]
Hi, good question. There is no real nesting at the constraints level, but you could easily create the illusion of nesting though. When you create a view using some constraints, you can then create additional constraints which refer to that view. For instance, by creating a constraint which has 50% of the width of another view. I've tried to illustrate this with use of the explicit constraint syntax in the following vfl:

```
// Define parent view using regular evfl
H:|~[view(50%)]~|
V:|~[view(50%)]~|

// Define subView in relation to view
C:subView.centerX(view.centerX)     // subView is horizontally centered to view
C:subView.centerY(view.centerY)     // subView is vertically centered to view
C:subView.width(view.width/2)       // subView is half the width of view
C:subView.height(view.height/2)     // subView is half the height of view

// Place subView in front of view
Z:[view][subView]
```

[Just copy & paste the VFL into the visual format editor to see the result of this.](https://rawgit.com/IjzerenHein/visualformat-editor/master/dist/index.html)
