### ISSUE TITLE
Fatality on iPhone 7

### ISSUE THREAD

**Issue by msqaddura** [IjzerenHein/autolayout.js#23]
Hello, 
I am using v0.7.0
applying the following lines below:
```
//spacing:2
V:|~[box]~|
H:|-(20)-[box(170)]~|
V:[box:-[r0(40)][r1(r0)][r2(r0)][r3(r0)][r4(r0)]-[r5(r0)][r6(70)]-[r7(r0)][r8(r6)]-]
H:[r1:-[x0]-[y0(x0)]-]
H:[r2:-[x1]-[y1(x1)]-]
H:[r3:-[x2]-[y2(x2)]-]
H:[r4:-[x3]-[y3(x3)]-]
H:[r6:[A][B(A)]]
H:[r8:[C][D(C)]]
```
on this editor : 
https://rawgit.com/IjzerenHein/visualformat-editor/master/dist/index.html?vfl=example

result is : 
![image](https://cloud.githubusercontent.com/assets/11808840/26206717/3e2d9654-3bee-11e7-9ffd-00c790b22956.png)

so that is pretty fine, until I try it on iphone7 and my heart gets broken into little tiny pieces 💔 

I tried many variances but it always threw these errors on iPhone7 
1) Undefined is not an object (evaluating 'a.isResricted')
2) Undefined is not an object (evaluating 'a.hashCode' )
3) https://github.com/IjzerenHein/autolayout.js/issues/21 (same issue same workaround so no problem) 

So it could be either me writing it the wrong way or there is a bug in the library. or bitter truth both of us which is most likely to be happening.

Also, my vfl could be messed up, it will be much appreciated if you could tell me a better way of writing it as am not so vfl savvy

Thank you in advance, 
keep the good work up 👍

**Comment by IjzerenHein** [comment]
Hi, thanks for letting me know of the problem. I'll get back to you later when I have more time on my hands. As for the `hashcode` problem, please take a look at my last message in this thread https://github.com/IjzerenHein/autolayout.js/issues/22
cheers
