### ISSUE TITLE
How to do something like media queries and size breakpoints?

### ISSUE THREAD

**Issue by trusktr** [IjzerenHein/autolayout.js#29]
How can we change the layout at differing container sizes? f.e., maybe when window width is bigger than some value I want to have a different layout.

[`react-autolayout`](https://github.com/fattenap/react-autolayout) has something like this, see in the README example.

Is there something like this with AutoLayout.js?

**Comment by IjzerenHein** [comment]
Hi Joe. That area is not addressed by autolayout or the underlying constrain system. You should handle selection of different layouts at a higher level.

You can set the maximum/minimum size of views though, by using rules like `<=400`.
