### ISSUE TITLE
Percentage constraints produces fractional extends

### ISSUE THREAD

**Issue by mcbain** [IjzerenHein/autolayout.js#6]
Applied to a size of e.g. 101 produces 50.5 as width for 'a'. Allow settings to force integer values only.

```
H:|-[a(==50%)]-[b]-|
V:|-[a(b),b]-|
```

**Comment by IjzerenHein** [comment]
That's an interesting problem, I'd have to think about on how to achieve the desired results.
So give the following vfl, what would your expected results be?

Width: 101
```vfl
H:|[a(50%)][b]|
```

a: 50, b: 51 ?

**Comment by mcbain** [comment]
Using the fractional values to set a <div> position or size, will work but leads to blurry result sometimes.
For the example provided 50,51 could be valid solution, when pos and size are rounded similarly.

**Comment by IjzerenHein** [comment]
I could imagine the following syntax for integer rounding, giving you significant control of how rounding is performed:

```vfl
H:|[a(round(50%))]|
H:|[b(floor(50%))]|
H:|[c(ceil(50%))]|
```

What do you think of this?

**Comment by mcbain** [comment]
perfect :)
